# GraphQL Config for GraphQL-Markdown documentation generation
schema: "./src/main/resources/graphql/schema.graphqls"
extensions:
  graphql-markdown:
    rootPath: "./docs"       # output folder for generated documentation
    baseURL: "."             # write files directly into ./docs
    homepage: "./docs/README.md"
    # Loaders: for local SDL files
    loaders:
      GraphQLFileLoader:
        module: "@graphql-tools/graphql-file-loader"
