spring.application.name=demo

# GraphQL Configuration
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
spring.graphql.schema.locations=classpath:graphql/
spring.graphql.schema.file-extensions=graphql

# Debug GraphQL
logging.level.org.springframework.graphql=DEBUG
logging.level.com.graphQl.demo=DEBUG
